//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BnsXmlEditor.Properties
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BnsXmlEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to In the field for autoId, only numbers can be present..
        /// </summary>
        internal static string AutoIdContainsOnlyNumbersMessage
        {
            get
            {
                return ResourceManager.GetString("AutoIdContainsOnlyNumbersMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copying the value of this field is not supported..
        /// </summary>
        internal static string CopingFieldNotSupported
        {
            get
            {
                return ResourceManager.GetString("CopingFieldNotSupported", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Item not found.
        /// </summary>
        internal static string ElementNotFoundedCaption
        {
            get
            {
                return ResourceManager.GetString("ElementNotFoundedCaption", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An element with autoId {0} was not found. {1} Check the entered value or reset the filter..
        /// </summary>
        internal static string ElementNotFoundedMessage
        {
            get
            {
                return ResourceManager.GetString("ElementNotFoundedMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorCaption
        {
            get
            {
                return ResourceManager.GetString("ErrorCaption", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid file format..
        /// </summary>
        internal static string InvalidFileFormat
        {
            get
            {
                return ResourceManager.GetString("InvalidFileFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The language is changed. For the changes to take effect, please restart the application..
        /// </summary>
        internal static string LanguageChangedMessage
        {
            get
            {
                return ResourceManager.GetString("LanguageChangedMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string QuestionCaption
        {
            get
            {
                return ResourceManager.GetString("QuestionCaption", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Processed {0} items..
        /// </summary>
        internal static string ReplaceSuccessMessage
        {
            get
            {
                return ResourceManager.GetString("ReplaceSuccessMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the changes?.
        /// </summary>
        internal static string SaveChangesQuestionMessage
        {
            get
            {
                return ResourceManager.GetString("SaveChangesQuestionMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No radio buttons have been selected for searching..
        /// </summary>
        internal static string SearchFieldNotSelected
        {
            get
            {
                return ResourceManager.GetString("SearchFieldNotSelected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Operation completed.
        /// </summary>
        internal static string SuccessCaption
        {
            get
            {
                return ResourceManager.GetString("SuccessCaption", resourceCulture);
            }
        }
    }
}
